### ISSUE TITLE
"ValueError: I/O operation on closed pipe" on Windows systems

### ISSUE THREAD

**Issue by danyathecoder** [raznem/parsera#16]
On Windows systems, after the site was parsed successfully occurs the following error:
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000015EEA08C2C0>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

It looks like an error related to `asyncio` library on Windows systems. The incompatibility of packages could cause this.

System tested: Windows 11, python 3.12

**Comment by ThomasVuNguyen** [comment]
Having the same issue!

**Comment by danyathecoder** [comment]
@ThomasVuNguyen  I highly advise you to use Docker for running Parsera because `asyncio` library doesn't work stable on the Windows systems
