### ISSUE TITLE
Add ollama support.

### ISSUE THREAD

**Issue by mmar58** [raznem/parsera#5]
Hi, ollama runs offline on personal computer or laptop. So enabling ollama in website scraping will give a boost to end users and developer. They can test it freely.

And moreover, ollama also has python API. So if you can do this, it will be greater good for developers. Also your project will get a boost as it will enable developer to test and develop by keeping everything inside his computer. Will be also good for privacy concerns.

**Comment by XD-coder** [comment]
Also, using ollama makes it easier to interchange models and future proof in case there are new models that would work better with this perticular project

**Comment by cognitivetech** [comment]
+1

**Comment by spinagon** [comment]
Langchain supports it https://python.langchain.com/v0.2/docs/integrations/chat/ollama/ so you should be able to just use it

**Comment by raznem** [comment]
@SamTheCoder777 implemented HuggingFace `Transformers` support, which can be a way to go for a quick local run atm.

**Comment by lormayna** [comment]
I tried with Ollama but unfortunately no luck:

```
from langchain_ollama.llms import OllamaLLM
from parsera import Parsera
scraper = Parsera(model=llm)
url = "https://news.ycombinator.com/"
elements = {
        "Title": "News title",
        "Points": "Number of points",
        "Comments": "Number of comments",
}
result = scraper.run(url=url, elements=elements)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/parsera/parsera.py", line 47, in run
    return asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/parsera/parsera.py", line 43, in _run
    result = await extractor_instance.run()
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/parsera/engine/simple_extractor.py", line 46, in run
    output = await self.model.ainvoke(messages)
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 408, in ainvoke
    llm_result = await self.agenerate_prompt(
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 760, in agenerate_prompt
    return await self.agenerate(
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1183, in agenerate
    output = await self._agenerate_helper(
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1023, in _agenerate_helper
    raise e
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1007, in _agenerate_helper
    await self._agenerate(
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_ollama/llms.py", line 323, in _agenerate
    final_chunk = await self._astream_with_aggregation(
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_ollama/llms.py", line 240, in _astream_with_aggregation
    async for stream_resp in self._acreate_generate_stream(prompt, stop, **kwargs):
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_ollama/llms.py", line 194, in _acreate_generate_stream
    async for part in await self._async_client.generate(
  File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/pydantic/fields.py", line 926, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ModelPrivateAttr' object has no attribute 'generate'
```

**Comment by XD-coder** [comment]
> I tried with Ollama but unfortunately no luck:
> 
> ```
> from langchain_ollama.llms import OllamaLLM
> from parsera import Parsera
> scraper = Parsera(model=llm)
> url = "https://news.ycombinator.com/"
> elements = {
>         "Title": "News title",
>         "Points": "Number of points",
>         "Comments": "Number of comments",
> }
> result = scraper.run(url=url, elements=elements)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/parsera/parsera.py", line 47, in run
>     return asyncio.run(
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/parsera/parsera.py", line 43, in _run
>     result = await extractor_instance.run()
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/parsera/engine/simple_extractor.py", line 46, in run
>     output = await self.model.ainvoke(messages)
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 408, in ainvoke
>     llm_result = await self.agenerate_prompt(
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 760, in agenerate_prompt
>     return await self.agenerate(
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1183, in agenerate
>     output = await self._agenerate_helper(
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1023, in _agenerate_helper
>     raise e
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1007, in _agenerate_helper
>     await self._agenerate(
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_ollama/llms.py", line 323, in _agenerate
>     final_chunk = await self._astream_with_aggregation(
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_ollama/llms.py", line 240, in _astream_with_aggregation
>     async for stream_resp in self._acreate_generate_stream(prompt, stop, **kwargs):
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/langchain_ollama/llms.py", line 194, in _acreate_generate_stream
>     async for part in await self._async_client.generate(
>   File "/home/lorenzo/progetti/rasenna/references-extractor/lib/python3.10/site-packages/pydantic/fields.py", line 926, in __getattr__
>     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
> AttributeError: 'ModelPrivateAttr' object has no attribute 'generate'
> ```
> 
> If I try to install the parsera and langchain-ollama in a brand new virtualenv, I am getting this error:
> 
> ```
> >>> from langchain_ollama.llms import OllamaLLM
> >>> from parsera import Parsera
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/parsera/__init__.py", line 1, in <module>
>     from parsera.parsera import ExtractorType, Parsera, ParseraScript
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/parsera/parsera.py", line 8, in <module>
>     from parsera.engine.model import GPT4oMiniModel
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/parsera/engine/model.py", line 14, in <module>
>     from langchain_openai import AzureChatOpenAI, ChatOpenAI
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/langchain_openai/__init__.py", line 1, in <module>
>     from langchain_openai.chat_models import AzureChatOpenAI, ChatOpenAI
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/langchain_openai/chat_models/__init__.py", line 1, in <module>
>     from langchain_openai.chat_models.azure import AzureChatOpenAI
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/langchain_openai/chat_models/azure.py", line 41, in <module>
>     from langchain_openai.chat_models.base import BaseChatOpenAI
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 379, in <module>
>     class BaseChatOpenAI(BaseChatModel):
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 463, in BaseChatOpenAI
>     def build_extra(cls, values: Dict[str, Any]) -> Dict[str, Any]:
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/pydantic/v1/class_validators.py", line 134, in dec
>     f_cls = _prepare_validator(f, allow_reuse)
>   File "/home/lorenzo/progetti/rasenna/scraper/lib/python3.10/site-packages/pydantic/v1/class_validators.py", line 156, in _prepare_validator
>     raise ConfigError(f'duplicate validator function "{ref}"; if this is intended, set `allow_reuse=True`')
> pydantic.v1.errors.ConfigError: duplicate validator function "langchain_openai.chat_models.base.BaseChatOpenAI.build_extra"; if this is intended, set `allow_reuse=True`
> ```

**Comment by gg-91** [comment]
It seems you now need to buy some openai usage credits to use this. I kept getting RateLimitError 429 otherwise.

openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

**Comment by raznem** [comment]
@lormayna @XD-coder can you provide a full code snippet, cause this one is missing the LLM initialization part?

**Comment by raznem** [comment]
A new `v0.2.2` is out, now we have official `ollama` support.  
[Here](https://docs.parsera.org/features/custom-models/#run-local-model-with-ollama) you can find the instruction of running Parsera with ollama.
